defaults: &defaults
  pool: 5
  timeout: 5000
  encoding: utf8
  <<: *<%= ENV['RAILS_DB'] || "pg" %>

postgresql: &postgresql
  adapter: postgresql
  encoding: utf8
  database: react_crm
  username: lumen
  password:
  # host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  # port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
  # min_messages: ERROR
  # reconnect: false


development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
