export const LOAD_LEADS_SUCCESS = 'LOAD_LEADS_SUCCESS';
export const CREATE_LEAD_SUCCESS = 'CREATE_LEAD_SUCCESS';
export const LOAD_LEAD_SUCCESS = 'LOAD_LEAD_SUCCESS';
export const UPDATE_LEAD_SUCCESS = 'UPDATE_LEAD_SUCCESS';
export const DELETE_LEAD_SUCCESS = 'DELETE_LEAD_SUCCESS';
